name: Update App Version

on:
  push:
    branches: [ main ]

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update app version (with token)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run vb

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add package.json
          git commit -m "[skip actions] Update app version to $(npm pkg get version)" || true

      - name: Push changes
        run: git push origin HEAD:${{ github.sha }}

